name: Trigger auto deployment for container-app-5nb5nkpqsw6sc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-5nb5nkpqsw6sc-AutoDeployTrigger-098e9f36-3500-409f-94ac-a021cd7d92e3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5NB5NKPQSW6SC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5NB5NKPQSW6SC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5NB5NKPQSW6SC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5NB5NKPQSW6SC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5NB5NKPQSW6SC_REGISTRY_PASSWORD }}
          containerAppName: container-app-5nb5nkpqsw6sc
          resourceGroup: todonodejsa260
          imageToBuild: default/container-app-5nb5nkpqsw6sc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


